language: ruby
rvm:
  - 2.4
install: bundle install
script: jekyll build
deploy:
  - provider: s3
    access_key_id: $AWS_S3_KEY
    secret_access_key: $AWS_S3_SECRET
    bucket: developer-guides.austintexas.io
    skip_cleanup: true
    region: us-east-1
    local_dir: _site
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_S3_KEY
    secret_access_key: $AWS_S3_SECRET
    bucket: coa-developer-guides
    skip_cleanup: true
    region: us-east-1
    local_dir: _site
    on:
      branch: staging